### PR TITLE
feat: Implementing

### PR DESCRIPTION
**Pull request by hoyangtsai**
## 💡 Background and solution

1. I was using [react-image-crop](https://github.com/DominicTobias/react-image-crop) to implement, but it was not fully apply the requirements. I just kept it along.
2. So I went another way to implement which is after uploading an image, set the image as a canvas background, the user can draw a rectangle on it, and resize, re-position, delete each of them.

localhost_3000

## 🤔 TODO

1. Beautify the delete icon.

## ☑️ Self Check before Merge

- [x] Doc and Wiki are updated/provided or not needed.
- [x] Followed the Commit Message Guidelines listed in CONTRIBUTING.md

### CODE REVIEW

**Comment by hoyangtsai** [comment]
Update commit message

**Comment by hoyangtsai** [comment]
I already amended the commit message, but I still got the commit-lint-pr error.
I don't know where I did wrong.

**Comment by Joseph7451797** [comment]
> I already amended the commit message, but I still got the commit-lint-pr error.
> I don't know where I did wrong.

To fix the error, you should modify the PR title to comply with the commit message rule.

**Comment by hoyangtsai** [comment]
> > I already amended the commit message, but I still got the commit-lint-pr error.
> > I don't know where I did wrong.
> 
> To fix the error, you should modify the PR title to comply with the commit message rule.

OK. I changed the PR title, but it's not resolved.

**Pull request closed without merging**
