### PR TITLE
Crescendo Lab home assignment - SHU-LIN LU 

### PR DESCRIPTION
**Pull request by greeeenlu**
## ☑️ Self Check before Merge

- [ ] Doc and Wiki are updated/provided or not needed.
- [ ] Followed the Commit Message Guidelines listed in CONTRIBUTING.md

### CODE REVIEW

**Comment by Joseph7451797** [comment]
I'm curious about the inconsistent indentation in this PR. What kind of editor did you use?

**Comment by Joseph7451797** [comment]
I'm curious about the inconsistent indentation in this PR. What kind of editor did you use?

**Comment by greeeenlu** [comment]
> I'm curious about the inconsistent indentation in this PR. What kind of editor did you use?
VS Code

**Comment by Joseph7451797** [comment]
> > I'm curious about the inconsistent indentation in this PR. What kind of editor did you use?
> > VS Code

Got it. Thank you for the reply.

**Pull request closed without merging**
